### ISSUE TITLE
A user should be able to delete a survey point. 

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#256]
Most likely they entered the point by accident and no images are associated. If images are associated with the survey point then all images can be moved to a "general" survey point named Default (or something similar).

**Comment by ericboucher** [comment]
@drewjgray in what field would we want this to happen? It is quite easy for those with access to the database to do it upon request for now.

@avalmas-programize can you just make sure that we set null on deletes?

**Comment by drewjgray** [comment]
We want this to be available as a feature to the users, not for DB admins. Can we put a minus sign next to a survey point in the dropdown menu?

**Comment by ericboucher** [comment]
It will be a bit tricky since it's not a standard UI at all but we can try.

I definitely think this should be a functionality for users as well but I was seeing that as more of a post mvp feature that comes on a dedicated page with other admin edit features for surveys / reefs

If you would like us to investigate the first option, how about:
 - we try to add a `x` or a garbage can at the end of every row in the drop down
 - add a confirmation message on click: `Are you sure that you would like to delete "survey point" for all your surveys?`

**Comment by drewjgray** [comment]
That looks good to me. I think it is important for MVP because the first time I tried to use it, I wanted to delete a point, and the first time John tried to use it, he tried to delete point - seems like a thing people are going to do.

**Comment by ericboucher** [comment]
Note - As we work on this, let's improve `website/src/common/SurveyForm/index.tsx` and:
- move it out of `common`
- use classes to style components instead of inline styling
